
name: Terraform
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup tf
        uses: hashicorp/setup-terraform@v3
        with:
          terraform-version: '1.7.0'
      - name: tf init
        run: terraform init
      - name: tf validate
        run: terraform validate
      - name: tf plan
        run: terraform plan --out=my-plan.tfplan
      - name: upload plan by artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-plan.tfplan
          path: my-plan.tfplan
      - name: verified
        run: ls -lR

  second:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup tf
        uses: hashicorp/setup-terraform@v3
        with:
          terraform-version: '1.7.0'
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-plan.tfplan
      - name: steps in pipeline
        run: terraform init && terraform validate && terraform apply -input=false
      - name: verification
        run: ls -lR
